wasm:
 rustup toolchain install nightly
 rustup target add wasm32-unknown-unknown --toolchain nightly
 rustup default nightly-aarch64-apple-darwin
 AR=/opt/homebrew/opt/llvm/bin/llvm-ar CC=/opt/homebrew/opt/llvm/bin/clang wasm-pack build --target web --no-typescript

