wasm:
  AR=/opt/homebrew/opt/llvm/bin/llvm-ar \
  CC=/opt/homebrew/opt/llvm/bin/clang \
  wasm-pack build \
    --target web \
    --out-name bip322 \
    www
  cp www/pkg/bip322.js www/pkg/bip322_bg.wasm src

install:
  npm install

run: install wasm
  npm run dev

lint: install
  npm run lint

